In [5]:
import os
import pandas as pd
import numpy as np
import librosa
from tqdm import tqdm

In [6]:
# Define file paths
metadata_path = 'fma_metadata/tracks.csv' 
audio_dir = 'dataset'

In [7]:
tracks = pd.read_csv(metadata_path, header=[0,1], index_col=0)

In [8]:
print(tracks)

            album                                                     \
         comments         date_created        date_released engineer
track_id
2               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
3               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
5               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
10              0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN
20              0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN
...           ...                  ...                  ...      ...
155316          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155317          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155318          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155319          0  2017-03-30 15:20:35  2017-02-17 00:00:00      NaN
155320          0  2017-03-26 16:22:18  2017-03-26 00:00:00      NaN

                                                                              \
         favorites     id                                        information
track_id
2                4      1                                            <p></p>
3                4      1                                            <p></p>
5                4      1                                            <p></p>
10               4      6                                                NaN
20               2      4          <p>Â "spiritual songs" from Nicky Cook</p>
...            ...    ...                                                ...
155316           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155317           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155318           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155319           0  22940  <p>A live performance at Monty Hall on Feb 17,...
155320           1  22906                                                NaN

                               \
         listens     producer
track_id
2           6073          NaN
3           6073          NaN
5           6073          NaN
10         47632          NaN
20          2710          NaN
...          ...          ...
155316      1506  Monty Hall
155317      1506  Monty Hall
155318      1506  Monty Hall
155319      1506  Monty Hall
155320      7481          NaN

                                                             ...       track  \
                                                       tags  ... information
track_id                                                     ...
2                                                        []  ...         NaN
3                                                        []  ...         NaN
5                                                        []  ...         NaN
10                                                       []  ...         NaN
20                                                       []  ...         NaN
...                                                     ...  ...         ...
155316                                                   []  ...         NaN
155317                                                   []  ...         NaN
155318                                                   []  ...         NaN
155319                                                   []  ...         NaN
155320    ['ballad', 'epic', 'rockabilly', 'curse', 'hex...  ...         NaN

                                 \
         interest language_code
track_id
2            4656            en
3            1470            en
5            1933            en
10          54881            en
20            978            en
...           ...           ...
155316        122           NaN
155317        194           NaN
155318        214           NaN
155319        336           NaN
155320        972           NaN

                                                                              \
                                                    license listens lyricist
track_id
2         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1293      NaN
3         Attribution-NonCommercial-ShareAlike 3.0 Inter...     514      NaN
5         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1151      NaN
10        Attribution-NonCommercial-NoDerivatives (aka M...   50135      NaN
20        Attribution-NonCommercial-NoDerivatives (aka M...     361      NaN
...                                                     ...     ...      ...
155316    Creative Commons Attribution-NonCommercial-NoD...     102      NaN
155317    Creative Commons Attribution-NonCommercial-NoD...     165      NaN
155318    Creative Commons Attribution-NonCommercial-NoD...     168      NaN
155319    Creative Commons Attribution-NonCommercial-NoD...     294      NaN
155320                            Attribution-NonCommercial     705      NaN

                                                                              \
         number publisher                                               tags
track_id
2             3       NaN                                                 []
3             4       NaN                                                 []
5             6       NaN                                                 []
10            1       NaN                                                 []
20            3       NaN                                                 []
...         ...       ...                                                ...
155316        3       NaN                                                 []
155317        4       NaN                                                 []
155318        6       NaN                                                 []
155319        5       NaN                                                 []
155320        7       NaN  ['ballad', 'epic', 'rockabilly', 'curse', 'hex...


                                              title
track_id
2                                              Food
3                                      Electric Ave
5                                        This World
10                                          Freeway
20                                  Spiritual Level
...                                             ...
155316                                    The Auger
155317                              Let's Skin Ruby
155318           My House Smells Like Kim Deal/Pulp
155319                      The Man With Two Mouths
155320    Another Trick Up My Sleeve (Instrumental)

[106574 rows x 52 columns]

In [9]:
medium_tracks = tracks[tracks['set', 'subset'] == 'medium']

In [10]:
medium_tracks

            album                                                            \
         comments         date_created        date_released        engineer
track_id
3               0  2008-11-26 01:44:45  2009-01-05 00:00:00             NaN
134             0  2008-11-26 01:44:45  2009-01-05 00:00:00             NaN
136             1  2008-11-26 01:49:19  2009-01-07 00:00:00             NaN
139             0  2008-11-26 01:49:57  2009-01-16 00:00:00             NaN
181             0  2008-11-26 01:52:15  2007-04-13 00:00:00             NaN
...           ...                  ...                  ...             ...
155297          0  2017-03-30 09:50:32  2017-03-30 00:00:00             NaN
155298          0  2017-03-30 10:45:13                  NaN             NaN
155306          0  2017-03-30 10:45:13                  NaN             NaN
155307          0  2017-03-30 12:51:05  2017-03-27 00:00:00  Scott Williams
155314          0  2017-03-30 15:20:35  2017-02-17 00:00:00             NaN

                                                                              \
         favorites     id                                        information
track_id
3                4      1                                            <p></p>
134              4      1                                            <p></p>
136              0     58  <p>A couple of unreleased mp3s from the fellas...
139              1     60  <p>A full ensamble of strings, drums, electron...
181              0     79  <p>This Human Ear Music reissue compiles a âBe...
...            ...    ...                                                ...
155297           1  22935  <p>The stars will show you the way in this unp...
155298           0  22936                                                NaN
155306           0  22936                                                NaN
155307           0  22937  <p>Scott welcomes Russian revolutionary avant ...
155314           0  22940  <p>A live performance at Monty Hall on Feb 17,...

                                       ...       track                         \
         listens        producer tags  ... information interest language_code
track_id                               ...
3           6073             NaN   []  ...         NaN     1470            en
134         6073             NaN   []  ...         NaN     1126            en
136         3331             NaN   []  ...         NaN     1948            en
139         1304             NaN   []  ...         NaN      702            en
181         1339             NaN   []  ...         NaN     1736            en
...          ...             ...  ...  ...         ...      ...           ...
155297      6196             NaN   []  ...         NaN     1463           NaN
155298      2454             NaN   []  ...         NaN      706           NaN
155306      2454             NaN   []  ...         NaN      497           NaN
155307      1206  Scott Williams   []  ...         NaN      630           NaN
155314      1506     Monty Hall    []  ...         NaN      778           NaN

                                                                              \
                                                    license listens lyricist
track_id
3         Attribution-NonCommercial-ShareAlike 3.0 Inter...     514      NaN
134       Attribution-NonCommercial-ShareAlike 3.0 Inter...     943      NaN
136       Attribution-NonCommercial-ShareAlike 3.0 Inter...    1498      NaN
139       Attribution-Noncommercial-No Derivative Works ...     582      NaN
181       Attribution-Noncommercial-No Derivative Works ...    1339      NaN
...                                                     ...     ...      ...
155297                            Attribution-NonCommercial    1049      NaN
155298                                          Attribution     590      NaN
155306                                          Attribution     435      NaN
155307    Creative Commons Attribution-NonCommercial-NoD...     571      NaN
155314    Creative Commons Attribution-NonCommercial-NoD...     652      NaN


         number publisher tags                       title
track_id
3             4       NaN   []                Electric Ave
134           5       NaN   []                Street Music
136           0       NaN   []  Peel Back The Mountain Sky
139           2       NaN   []                    CandyAss
181           1       NaN   []                 Gopacapulco
...         ...       ...  ...                         ...
155297        9       NaN   []               Nebula Reborn
155298        2       NaN   []             An Idiot Abroad
155306        1       NaN   []                    Tiny Man
155307        1       NaN   []                       Kolka
155314        2       NaN   []                Miracle Grow

[17000 rows x 52 columns]

In [11]:
audio_files = []
for root, dirs, files in os.walk(audio_dir):
    for file in files:
        if file.endswith('.mp3'):
            audio_files.append(os.path.join(root, file))

In [12]:
audio_files

['dataset\\104003.mp3',
 'dataset\\104004.mp3',
 'dataset\\104005.mp3',
 'dataset\\104006.mp3',
 'dataset\\104008.mp3',
 'dataset\\104009.mp3',
 'dataset\\104010.mp3',
 'dataset\\104011.mp3',
 'dataset\\104012.mp3',
 'dataset\\104013.mp3',
 'dataset\\104014.mp3',
 'dataset\\104015.mp3',
 'dataset\\104016.mp3',
 'dataset\\104017.mp3',
 'dataset\\104018.mp3',
 'dataset\\104019.mp3',
 'dataset\\104020.mp3',
 'dataset\\104021.mp3',
 'dataset\\104022.mp3',
 'dataset\\104023.mp3',
 'dataset\\104024.mp3',
 'dataset\\104025.mp3',
 'dataset\\104026.mp3',
 'dataset\\104027.mp3',
 'dataset\\104028.mp3',
 'dataset\\104029.mp3',
 'dataset\\104030.mp3',
 'dataset\\104031.mp3',
 'dataset\\104032.mp3',
 'dataset\\104033.mp3',
 'dataset\\104034.mp3',
 'dataset\\104035.mp3',
 'dataset\\104036.mp3',
 'dataset\\104037.mp3',
 'dataset\\104038.mp3',
 'dataset\\104039.mp3',
 'dataset\\104040.mp3',
 'dataset\\104041.mp3',
 'dataset\\104042.mp3',
 'dataset\\104043.mp3',
 'dataset\\104044.mp3',
 'dataset\\104045.mp3',
 'dataset\\104046.mp3',
 'dataset\\104047.mp3',
 'dataset\\104048.mp3',
 'dataset\\104049.mp3',
 'dataset\\104050.mp3',
 'dataset\\104056.mp3',
 'dataset\\104057.mp3',
 'dataset\\104058.mp3',
 'dataset\\104059.mp3',
 'dataset\\104060.mp3',
 'dataset\\104061.mp3',
 'dataset\\104062.mp3',
 'dataset\\104063.mp3',
 'dataset\\104064.mp3',
 'dataset\\104065.mp3',
 'dataset\\104066.mp3',
 'dataset\\104067.mp3',
 'dataset\\104068.mp3',
 'dataset\\104069.mp3',
 'dataset\\104070.mp3',
 'dataset\\104071.mp3',
 'dataset\\104072.mp3',
 'dataset\\104073.mp3',
 'dataset\\104074.mp3',
 'dataset\\104085.mp3',
 'dataset\\104086.mp3',
 'dataset\\104087.mp3',
 'dataset\\104088.mp3',
 'dataset\\104097.mp3',
 'dataset\\104098.mp3',
 'dataset\\104099.mp3',
 'dataset\\104100.mp3',
 'dataset\\104101.mp3',
 'dataset\\104102.mp3',
 'dataset\\104103.mp3',
 'dataset\\104104.mp3',
 'dataset\\104105.mp3',
 'dataset\\104106.mp3',
 'dataset\\104107.mp3',
 'dataset\\104108.mp3',
 'dataset\\104110.mp3',
 'dataset\\104111.mp3',
 'dataset\\104112.mp3',
 'dataset\\104113.mp3',
 'dataset\\104114.mp3',
 'dataset\\104115.mp3',
 'dataset\\104116.mp3',
 'dataset\\104117.mp3',
 'dataset\\104118.mp3',
 'dataset\\104119.mp3',
 'dataset\\104120.mp3',
 'dataset\\104121.mp3',
 'dataset\\104122.mp3',
 'dataset\\104123.mp3',
 'dataset\\104124.mp3',
 'dataset\\104125.mp3',
 'dataset\\104126.mp3',
 'dataset\\104127.mp3',
 'dataset\\104128.mp3',
 'dataset\\104129.mp3',
 'dataset\\104130.mp3',
 'dataset\\104131.mp3',
 'dataset\\104132.mp3',
 'dataset\\104133.mp3',
 'dataset\\104134.mp3',
 'dataset\\104135.mp3',
 'dataset\\104136.mp3',
 'dataset\\104137.mp3',
 'dataset\\104143.mp3',
 'dataset\\104144.mp3',
 'dataset\\104145.mp3',
 'dataset\\104146.mp3',
 'dataset\\104147.mp3',
 'dataset\\104148.mp3',
 'dataset\\104149.mp3',
 'dataset\\104150.mp3',
 'dataset\\104151.mp3',
 'dataset\\104152.mp3',
 'dataset\\104153.mp3',
 'dataset\\104154.mp3',
 'dataset\\104155.mp3',
 'dataset\\104156.mp3',
 'dataset\\104157.mp3',
 'dataset\\104158.mp3',
 'dataset\\104159.mp3',
 'dataset\\104160.mp3',
 'dataset\\104161.mp3',
 'dataset\\104162.mp3',
 'dataset\\104163.mp3',
 'dataset\\104164.mp3',
 'dataset\\104165.mp3',
 'dataset\\104166.mp3',
 'dataset\\104167.mp3',
 'dataset\\104168.mp3',
 'dataset\\104169.mp3',
 'dataset\\104170.mp3',
 'dataset\\104171.mp3',
 'dataset\\104172.mp3',
 'dataset\\104173.mp3',
 'dataset\\104174.mp3',
 'dataset\\104175.mp3',
 'dataset\\104176.mp3',
 'dataset\\104177.mp3',
 'dataset\\104179.mp3',
 'dataset\\104180.mp3',
 'dataset\\104181.mp3',
 'dataset\\104182.mp3',
 'dataset\\104183.mp3',
 'dataset\\104184.mp3',
 'dataset\\104185.mp3',
 'dataset\\104186.mp3',
 'dataset\\104187.mp3',
 'dataset\\104188.mp3',
 'dataset\\104189.mp3',
 'dataset\\104190.mp3',
 'dataset\\104191.mp3',
 'dataset\\104192.mp3',
 'dataset\\104193.mp3',
 'dataset\\104194.mp3',
 'dataset\\104195.mp3',
 'dataset\\104196.mp3',
 'dataset\\104197.mp3',
 'dataset\\104198.mp3',
 'dataset\\104199.mp3',
 'dataset\\104200.mp3',
 'dataset\\104201.mp3',
 'dataset\\104202.mp3',
 'dataset\\104203.mp3',
 'dataset\\104204.mp3',
 'dataset\\104205.mp3',
 'dataset\\104206.mp3',
 'dataset\\104207.mp3',
 'dataset\\104208.mp3',
 'dataset\\104209.mp3',
 'dataset\\104210.mp3',
 'dataset\\104211.mp3',
 'dataset\\104219.mp3',
 'dataset\\104220.mp3',
 'dataset\\104221.mp3',
 'dataset\\104222.mp3',
 'dataset\\104223.mp3',
 'dataset\\104224.mp3',
 'dataset\\104225.mp3',
 'dataset\\104226.mp3',
 'dataset\\104227.mp3',
 'dataset\\104228.mp3',
 'dataset\\104229.mp3',
 'dataset\\104230.mp3',
 'dataset\\104231.mp3',
 'dataset\\104232.mp3',
 'dataset\\104233.mp3',
 'dataset\\104234.mp3',
 'dataset\\104235.mp3',
 'dataset\\104236.mp3',
 'dataset\\104237.mp3',
 'dataset\\104238.mp3',
 'dataset\\104239.mp3',
 'dataset\\104240.mp3',
 'dataset\\104249.mp3',
 'dataset\\104250.mp3',
 'dataset\\104251.mp3',
 'dataset\\104252.mp3',
 'dataset\\104253.mp3',
 'dataset\\104254.mp3',
 'dataset\\104255.mp3',
 'dataset\\104256.mp3',
 'dataset\\104257.mp3',
 'dataset\\104258.mp3',
 'dataset\\104259.mp3',
 'dataset\\104260.mp3',
 'dataset\\104261.mp3',
 'dataset\\104262.mp3',
 'dataset\\104263.mp3',
 'dataset\\104264.mp3',
 'dataset\\104266.mp3',
 'dataset\\104267.mp3',
 'dataset\\104268.mp3',
 'dataset\\104269.mp3',
 'dataset\\104270.mp3',
 'dataset\\104271.mp3',
 'dataset\\104272.mp3',
 'dataset\\104273.mp3',
 'dataset\\104275.mp3',
 'dataset\\104276.mp3',
 'dataset\\104277.mp3',
 'dataset\\104278.mp3',
 'dataset\\104279.mp3',
 'dataset\\104282.mp3',
 'dataset\\104283.mp3',
 'dataset\\104284.mp3',
 'dataset\\104285.mp3',
 'dataset\\104286.mp3',
 'dataset\\104287.mp3',
 'dataset\\104288.mp3',
 'dataset\\104289.mp3',
 'dataset\\104290.mp3',
 'dataset\\104291.mp3',
 'dataset\\104292.mp3',
 'dataset\\104293.mp3',
 'dataset\\104294.mp3',
 'dataset\\104295.mp3',
 'dataset\\104296.mp3',
 'dataset\\104297.mp3',
 'dataset\\104298.mp3',
 'dataset\\104300.mp3',
 'dataset\\104303.mp3',
 'dataset\\104304.mp3',
 'dataset\\104305.mp3',
 'dataset\\104306.mp3',
 'dataset\\104324.mp3',
 'dataset\\104325.mp3',
 'dataset\\104326.mp3',
 'dataset\\104327.mp3',
 'dataset\\104332.mp3',
 'dataset\\104334.mp3',
 'dataset\\104340.mp3',
 'dataset\\104341.mp3',
 'dataset\\104342.mp3',
 'dataset\\104343.mp3',
 'dataset\\104344.mp3',
 'dataset\\104346.mp3',
 'dataset\\104347.mp3',
 'dataset\\104352.mp3',
 'dataset\\104353.mp3',
 'dataset\\104354.mp3',
 'dataset\\104355.mp3',
 'dataset\\104356.mp3',
 'dataset\\104357.mp3',
 'dataset\\104358.mp3',
 'dataset\\104359.mp3',
 'dataset\\104364.mp3',
 'dataset\\104366.mp3',
 'dataset\\104384.mp3',
 'dataset\\104385.mp3',
 'dataset\\104386.mp3',
 'dataset\\104387.mp3',
 'dataset\\104388.mp3',
 'dataset\\104389.mp3',
 'dataset\\104391.mp3',
 'dataset\\104392.mp3',
 'dataset\\104393.mp3',
 'dataset\\104394.mp3',
 'dataset\\104395.mp3',
 'dataset\\104396.mp3',
 'dataset\\104397.mp3',
 'dataset\\104398.mp3',
 'dataset\\104399.mp3',
 'dataset\\104400.mp3',
 'dataset\\104401.mp3',
 'dataset\\104402.mp3',
 'dataset\\104403.mp3',
 'dataset\\104404.mp3',
 'dataset\\104405.mp3',
 'dataset\\104406.mp3',
 'dataset\\104407.mp3',
 'dataset\\104408.mp3',
 'dataset\\104409.mp3',
 'dataset\\104410.mp3',
 'dataset\\104411.mp3',
 'dataset\\104412.mp3',
 'dataset\\104413.mp3',
 'dataset\\104423.mp3',
 'dataset\\104424.mp3',
 'dataset\\104425.mp3',
 'dataset\\104426.mp3',
 'dataset\\104427.mp3',
 'dataset\\104428.mp3',
 'dataset\\104430.mp3',
 'dataset\\104431.mp3',
 'dataset\\104432.mp3',
 'dataset\\104434.mp3',
 'dataset\\104573.mp3',
 'dataset\\104578.mp3',
 'dataset\\104579.mp3',
 'dataset\\104580.mp3',
 'dataset\\104581.mp3',
 'dataset\\104582.mp3',
 'dataset\\104583.mp3',
 'dataset\\104584.mp3',
 'dataset\\104585.mp3',
 'dataset\\104586.mp3',
 'dataset\\104587.mp3',
 'dataset\\104588.mp3',
 'dataset\\104589.mp3',
 'dataset\\104590.mp3',
 'dataset\\104591.mp3',
 'dataset\\104592.mp3',
 'dataset\\104593.mp3',
 'dataset\\104594.mp3',
 'dataset\\104595.mp3',
 'dataset\\104596.mp3',
 'dataset\\104597.mp3',
 'dataset\\104598.mp3',
 'dataset\\104599.mp3',
 'dataset\\104600.mp3',
 'dataset\\104601.mp3',
 'dataset\\104602.mp3',
 'dataset\\104603.mp3',
 'dataset\\104604.mp3',
 'dataset\\104605.mp3',
 'dataset\\104606.mp3',
 'dataset\\104607.mp3',
 'dataset\\104608.mp3',
 'dataset\\104609.mp3',
 'dataset\\104610.mp3',
 'dataset\\104611.mp3',
 'dataset\\104612.mp3',
 'dataset\\104613.mp3',
 'dataset\\104614.mp3',
 'dataset\\104615.mp3',
 'dataset\\104617.mp3',
 'dataset\\104618.mp3',
 'dataset\\104619.mp3',
 'dataset\\104620.mp3',
 'dataset\\104621.mp3',
 'dataset\\104622.mp3',
 'dataset\\104624.mp3',
 'dataset\\104625.mp3',
 'dataset\\104626.mp3',
 'dataset\\104627.mp3',
 'dataset\\104639.mp3',
 'dataset\\104640.mp3',
 'dataset\\104641.mp3',
 'dataset\\104642.mp3',
 'dataset\\104643.mp3',
 'dataset\\104644.mp3',
 'dataset\\104645.mp3',
 'dataset\\104646.mp3',
 'dataset\\104647.mp3',
 'dataset\\104648.mp3',
 'dataset\\104649.mp3',
 'dataset\\104650.mp3',
 'dataset\\104651.mp3',
 'dataset\\104652.mp3',
 'dataset\\104653.mp3',
 'dataset\\104654.mp3',
 'dataset\\104655.mp3',
 'dataset\\104656.mp3',
 'dataset\\104657.mp3',
 'dataset\\104658.mp3',
 'dataset\\104659.mp3',
 'dataset\\104660.mp3',
 'dataset\\104661.mp3',
 'dataset\\104662.mp3',
 'dataset\\104663.mp3',
 'dataset\\104665.mp3',
 'dataset\\104666.mp3',
 'dataset\\104667.mp3',
 'dataset\\104668.mp3',
 'dataset\\104669.mp3',
 'dataset\\104670.mp3',
 'dataset\\104671.mp3',
 'dataset\\104673.mp3',
 'dataset\\104674.mp3',
 'dataset\\104675.mp3',
 'dataset\\104676.mp3',
 'dataset\\104677.mp3',
 'dataset\\104678.mp3',
 'dataset\\104679.mp3',
 'dataset\\104680.mp3',
 'dataset\\104681.mp3',
 'dataset\\104682.mp3',
 'dataset\\104683.mp3',
 'dataset\\104684.mp3',
 'dataset\\104685.mp3',
 'dataset\\104686.mp3',
 'dataset\\104687.mp3',
 'dataset\\104688.mp3',
 'dataset\\104689.mp3',
 'dataset\\104690.mp3',
 'dataset\\104691.mp3',
 'dataset\\104692.mp3',
 'dataset\\104693.mp3',
 'dataset\\104694.mp3',
 'dataset\\104695.mp3',
 'dataset\\104696.mp3',
 'dataset\\104697.mp3',
 'dataset\\104698.mp3',
 'dataset\\104699.mp3',
 'dataset\\104700.mp3',
 'dataset\\104701.mp3',
 'dataset\\104702.mp3',
 'dataset\\104703.mp3',
 'dataset\\104704.mp3',
 'dataset\\104705.mp3',
 'dataset\\104706.mp3',
 'dataset\\104707.mp3',
 'dataset\\104708.mp3',
 'dataset\\104709.mp3',
 'dataset\\104710.mp3',
 'dataset\\104711.mp3',
 'dataset\\104712.mp3',
 'dataset\\104713.mp3',
 'dataset\\104716.mp3',
 'dataset\\104717.mp3',
 'dataset\\104718.mp3',
 'dataset\\104719.mp3',
 'dataset\\104720.mp3',
 'dataset\\104721.mp3',
 'dataset\\104722.mp3',
 'dataset\\104723.mp3',
 'dataset\\104724.mp3',
 'dataset\\104725.mp3',
 'dataset\\104726.mp3',
 'dataset\\104727.mp3',
 'dataset\\104728.mp3',
 'dataset\\104729.mp3',
 'dataset\\104730.mp3',
 'dataset\\104731.mp3',
 'dataset\\104732.mp3',
 'dataset\\104733.mp3',
 'dataset\\104734.mp3',
 'dataset\\104735.mp3',
 'dataset\\104736.mp3',
 'dataset\\104737.mp3',
 'dataset\\104738.mp3',
 'dataset\\104739.mp3',
 'dataset\\104740.mp3',
 'dataset\\104741.mp3',
 'dataset\\104742.mp3',
 'dataset\\104743.mp3',
 'dataset\\104744.mp3',
 'dataset\\104745.mp3',
 'dataset\\104746.mp3',
 'dataset\\104747.mp3']

In [13]:
len(audio_files)

467

In [14]:
# Create an empty DataFrame to store features
features_df = pd.DataFrame(columns=['track_id', 'duration', 'mfcc'])

In [15]:
features_df

Empty DataFrame
Columns: [track_id, duration, mfcc]
Index: []

In [16]:
# Function to extract MFCC features
def extract_mfcc_features(file_path, sr=22050):
    try:
        # Load audio file
        audio, sr = librosa.load(file_path, sr=sr)
        
        # Extract MFCC features
        mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=13)
        
        # Calculate duration
        duration = librosa.get_duration(y=audio, sr=sr)
        
        # Calculate mean of MFCC features
        mfcc_mean = np.mean(mfcc, axis=1)
        
        return duration, mfcc_mean.tolist()
    
    except (librosa.util.exceptions.ParameterError, Exception) as e:
        print(f"Error processing file {file_path}: {e}. Skipping this file.")
        return None, None

In [17]:
# Iterate over audio files with tqdm
for file_path in tqdm(audio_files[:1500], desc="Processing audio files"):
    track_id = int(os.path.basename(file_path)[:-4])
    duration, mfcc_features = extract_mfcc_features(file_path, sr=22050)
    
    if duration is not None and mfcc_features is not None:
        features_df.loc[len(features_df)] = {'track_id': track_id, 'duration': duration, 'mfcc': mfcc_features}

Processing audio files:   0%|          | 0/467 [00:00<?, ?it/s]

Processing audio files: 100%|ââââââââââ| 467/467 [01:16<00:00,  6.08it/s]

In [18]:
# Round duration and convert track_id to int
features_df['track_id'] = features_df['track_id'].astype(int)
features_df['duration'] = features_df['duration'].round(2)

In [19]:
# Print summary of features DataFrame
print("Summary of features:")
print(features_df)

Summary of features:
     track_id  duration                                               mfcc
0      104003     30.00  [-233.80906677246094, 175.17672729492188, 31.8...
1      104004     29.98  [-243.70809936523438, 174.11402893066406, 31.8...
2      104005     29.98  [-183.0714111328125, 132.3319549560547, -0.919...
3      104006     30.00  [-170.7470245361328, 139.9214324951172, -3.204...
4      104008     29.99  [-128.73458862304688, 107.98621368408203, -6.3...
..        ...       ...                                                ...
462    104743     29.98  [-224.8445281982422, 87.2147445678711, -8.2646...
463    104744     30.00  [-79.72381591796875, 127.87779998779297, -31.3...
464    104745     29.98  [-51.09634780883789, 92.99420166015625, 10.446...
465    104746     30.00  [-88.91748809814453, 59.30205154418945, -13.08...
466    104747     29.98  [-59.33289337158203, 88.89732360839844, -15.22...

[467 rows x 3 columns]

In [20]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

# Assuming 'features_df' has columns: 'track_id', 'duration', 'mfcc'

# Step 1: Convert 'mfcc' column from lists to arrays
features_df['mfcc'] = features_df['mfcc'].apply(np.array)

# Step 2: Normalize the 'mfcc' column
mfcc_scaler = MinMaxScaler()
features_df['mfcc_normalized'] = features_df['mfcc'].apply(lambda x: mfcc_scaler.fit_transform(x.reshape(-1, 1)).flatten())

# Step 3: Dimensionality Reduction
# Combine normalized MFCC features for dimensionality reduction
mfcc_normalized_features = np.stack(features_df['mfcc_normalized'])

# Applying PCA for dimensionality reduction
pca = PCA(n_components=2)  # You can adjust the number of components as per your requirement
pca_result = pca.fit_transform(mfcc_normalized_features)

# Create a DataFrame for PCA results
pca_df = pd.DataFrame(data=pca_result, columns=['PCA1', 'PCA2'])

# Concatenate PCA results with original DataFrame
features_df_with_pca = pd.concat([features_df[['track_id']], pca_df], axis=1)

# Now 'features_df_with_pca' contains 'track_id' along with PCA transformed features of 'mfcc'

In [21]:
features_df['PCA1'] = pca_df['PCA1']
features_df['PCA2'] = pca_df['PCA2']

In [22]:
features_df

,track_id,duration,mfcc,mfcc_normalized,PCA1,PCA2
0,104003,30.00,"[-233.80906677246094, 175.17672729492188, 31.8...","[0.0, 1.0, 0.6496703688610201, 0.7118033500585...",-0.350261,-0.044129
1,104004,29.98,"[-243.70809936523438, 174.11402893066406, 31.8...","[0.0, 1.0, 0.6594642155244953, 0.7284811980078...",-0.371300,-0.048055
2,104005,29.98,"[-183.0714111328125, 132.3319549560547, -0.919...","[0.0, 1.0, 0.5775218578898321, 0.7060632357334...",-0.343022,-0.002041
3,104006,30.00,"[-170.7470245361328, 139.9214324951172, -3.204...","[0.0, 1.0, 0.5392975399691198, 0.6643373899212...",-0.255524,-0.015101
4,104008,29.99,"[-128.73458862304688, 107.98621368408203, -6.3...","[0.0, 1.0, 0.5169734135420456, 0.6529083874034...",-0.081689,-0.048309
...,...,...,...,...,...,...
462,104743,29.98,"[-224.8445281982422, 87.2147445678711, -8.2646...","[0.0, 1.0, 0.6940345286283026, 0.8031356197594...",-0.669473,0.031512
463,104744,30.00,"[-79.72381591796875, 127.87779998779297, -31.3...","[0.0, 1.0, 0.23311424352404136, 0.587050952896...",0.379517,-0.009449
464,104745,29.98,"[-51.09634780883789, 92.99420166015625, 10.446...","[0.0, 1.0, 0.4271126687945478, 0.6785302884457...",0.231161,-0.047329
465,104746,30.00,"[-88.91748809814453, 59.30205154418945, -13.08...","[0.0, 1.0, 0.5116306870004921, 0.7938861861383...",-0.425361,0.119418
466,104747,29.98,"[-59.33289337158203, 88.89732360839844, -15.22...","[0.0, 1.0, 0.2975960957198094, 0.5217549372888...",0.383119,-0.074472

In [23]:
from pymongo import MongoClient

In [24]:
import pandas as pd
import numpy as np
from pymongo import MongoClient

# Assuming 'features_df' has columns: 'track_id', 'duration', 'mfcc', 'PCA1', 'PCA2'

# Convert NumPy arrays into lists
features_df['mfcc'] = features_df['mfcc'].apply(lambda x: x.tolist())
features_df['mfcc_normalized'] = features_df['mfcc_normalized'].apply(lambda x: x.tolist())

# Convert DataFrame to dictionary format
data_dict = features_df.to_dict(orient='records')

# Connect to MongoDB
client = MongoClient('localhost', 27017)  # Assuming MongoDB is running locally on the default port

# Access or create a database
db = client['bdaProject']  # Replace 'your_database_name' with your desired database name

# Access or create a collection
collection = db['extractedFeatures']  # Replace 'your_collection_name' with your desired collection name

# Insert data into MongoDB collection
collection.insert_many(data_dict)

# Close MongoDB connection
client.close()